version: "3"
services:
  postgres-dbs:
    image: library/postgres:13
    container_name: postgres-dbs
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  gatewayservice:
    container_name: gatewayservice
    image: gatewayservice
    build:
      context: lab3/gatewayservice
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/lab3/gatewayservice
    depends_on:
      - postgres-dbs
      - paymentservice
      - carsservice
      - rentalservice
  paymentservice:
    container_name: paymentservice
    image: paymentservice
    build:
      context: lab3/paymentservice
    restart: always
    ports:
      - "8050:8050"
    volumes:
      - .:/lab3/paymentservice
    depends_on:
      - postgres-dbs
  carsservice:
    container_name: carsservice
    image: carsservice
    build:
      context: lab3/carsservice
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - .:/lab3/carsservice
    depends_on:
      - postgres-dbs
  rentalservice:
    container_name: rentalservice
    image: rentalservice
    build:
      context: lab3/rentalservice
    restart: always
    ports:
      - "8060:8060"
    volumes:
      - .:/lab3/rentalservice
    depends_on:
      - postgres-dbs
volumes:
  db-data:
